org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.4
parchment_mappings_version=2024.12.22
minecraft_version=1.21.4
minecraft_version_range=[1.21.4,1.22)
neo_version=21.4.38-beta
neo_version_range=[21.4.0,)
loader_version_range=[4,)

citrus_lib_version=2.0.0-1.21.4
accessories_version=1.2.5-beta+1.21.4
modonomicon_version=1.108.3

mod_id=demeter
mod_name=Demeter
mod_license=GPL 3.0
mod_version=1.0.0
mod_group_id=dev.teamcitrus.demeter
mod_authors=ZestyBlaze
mod_description=A major overhaul of the vanilla farming system!
