modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/ZestyBlaze/Demeter/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://raw.githubusercontent.com/ZestyBlaze/Demeter/refs/heads/1.21.4-neo/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
#logoFile="examplemod.png"
credits="Thanks to Goomy for help coming up with animal names!"
authors="${mod_authors}"
description='''${mod_description}'''
featureFlags="META-INF/feature_flags.json"

[[mixins]]
    config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="curios"
    type="optional"
    versionRange="[11.0.1+1.21.5,)"
    ordering="NONE"
    side="BOTH"